---
##########################################################
# ansible

ansible_host: 192.168.40.5

##########################################################
# generic

console_interface: "{{ hostvars['testbed-manager.osism.local']['ansible_local']['testbed_network_devices']['management'] | default('ens3') }}"
management_interface: "{{ hostvars['testbed-manager.osism.local']['ansible_local']['testbed_network_devices']['internal'] | default('ens4') }}"

internal_address: 192.168.50.5
fluentd_host: 192.168.50.5

##########################################################
# cockpit

configure_cockpit_server: yes
cockpit_host: "{{ hostvars[inventory_hostname]['ansible_' + console_interface]['ipv4']['address'] }}"
cockpit_ssh_interface: "{{ hostvars['testbed-manager.osism.local']['ansible_local']['testbed_network_devices']['management'] | default('ens3') }}"

##########################################################
# netdata

netdata_host_type: server

##########################################################
# network-interfaces

network_allow_service_restart: no
network_restart_method: nothing

network_interfaces:
  - device: "{{ hostvars['testbed-manager.osism.local']['ansible_local']['testbed_network_devices']['management'] | default('ens3') }}"
    auto: true
    family: inet
    method: static
    address: 192.168.40.5
    netmask: 255.255.255.0
    gateway: 192.168.40.1
    mtu: 1450

  - device: "{{ hostvars['testbed-manager.osism.local']['ansible_local']['testbed_network_devices']['internal'] | default('ens4') }}"
    auto: true
    family: inet
    method: static
    address: 192.168.50.5
    netmask: 255.255.255.0
    mtu: 1450

  - device: "{{ hostvars['testbed-manager.osism.local']['ansible_local']['testbed_network_devices']['external'] | default('ens5') }}"
    auto: true
    family: inet
    method: static
    address: 192.168.90.5
    netmask: 255.255.255.0
    mtu: 1450

  - device: "{{ hostvars['testbed-manager.osism.local']['ansible_local']['testbed_network_devices']['provider'] | default('ens6') }}"
    auto: true
    family: inet
    method: static
    address: 192.168.100.5
    netmask: 255.255.255.0
    mtu: 1450

  - device: "{{ hostvars['testbed-manager.osism.local']['ansible_local']['testbed_network_devices']['storage_frontend'] | default('ens7') }}"
    auto: true
    family: inet
    method: static
    address: 192.168.70.5
    netmask: 255.255.255.0
    mtu: 1450

##########################################################
# kolla

network_interface: "{{ hostvars['testbed-manager.osism.local']['ansible_local']['testbed_network_devices']['internal'] | default('ens4') }}"
