---
##########################################################
# ansible

ansible_host: 192.168.40.10

##########################################################
# generic

console_interface: "{{ hostvars['testbed-node-0.osism.local']['ansible_local']['testbed_network_devices']['management'] | default('ens3') }}"
management_interface: "{{ hostvars['testbed-node-0.osism.local']['ansible_local']['testbed_network_devices']['internal'] | default('ens4') }}"

internal_address: 192.168.50.10
fluentd_host: 192.168.50.10

##########################################################
# cockpit

configure_cockpit_server: yes
cockpit_host: "{{ hostvars[inventory_hostname]['ansible_' + console_interface]['ipv4']['address'] }}"
cockpit_ssh_interface: "{{ hostvars['testbed-node-0.osism.local']['ansible_local']['testbed_network_devices']['management'] | default('ens3') }}"

##########################################################
# netdata

netdata_host_type: client

##########################################################
# network-interfaces

network_allow_service_restart: no
network_restart_method: nothing

network_interfaces:
  - device: "{{ hostvars['testbed-node-0.osism.local']['ansible_local']['testbed_network_devices']['management'] | default('ens3') }}"
    auto: true
    family: inet
    method: static
    address: 192.168.40.10
    netmask: 255.255.255.0
    gateway: 192.168.40.1
    mtu: 1450

  - device: "{{ hostvars['testbed-node-0.osism.local']['ansible_local']['testbed_network_devices']['internal'] | default('ens4') }}"
    auto: true
    family: inet
    method: static
    address: 192.168.50.10
    netmask: 255.255.255.0
    mtu: 1450

  - device: "{{ hostvars['testbed-node-0.osism.local']['ansible_local']['testbed_network_devices']['external'] | default('ens5') }}"
    auto: true
    family: inet
    method: static
    address: 192.168.90.10
    netmask: 255.255.255.0
    mtu: 1450

  - device: "{{ hostvars['testbed-node-0.osism.local']['ansible_local']['testbed_network_devices']['provider'] | default('ens6') }}"
    auto: true
    family: inet
    method: manual
    mtu: 1450

  - device: "{{ hostvars['testbed-node-0.osism.local']['ansible_local']['testbed_network_devices']['storage_frontend'] | default('ens7') }}"
    auto: true
    family: inet
    method: static
    address: 192.168.70.10
    netmask: 255.255.255.0
    mtu: 1450

  - device: "{{ hostvars['testbed-node-0.osism.local']['ansible_local']['testbed_network_devices']['storage_backend'] | default('ens8') }}"
    auto: true
    family: inet
    method: static
    address: 192.168.80.10
    netmask: 255.255.255.0
    mtu: 1450

##########################################################
# kolla

network_interface: "{{ hostvars['testbed-node-0.osism.local']['ansible_local']['testbed_network_devices']['internal'] | default('ens4') }}"

# api_interface:
# dns_interface:
kolla_external_vip_interface: "{{ hostvars['testbed-node-0.osism.local']['ansible_local']['testbed_network_devices']['external'] | default('ens5') }}"
# migration_interface:
neutron_external_interface: "{{ hostvars['testbed-node-0.osism.local']['ansible_local']['testbed_network_devices']['provider'] | default('ens6') }}"
# octavia_network_interface:
storage_interface: "{{ hostvars['testbed-node-0.osism.local']['ansible_local']['testbed_network_devices']['storage_frontend'] | default('ens7') }}"
# tunnel_interface:

##########################################################
# ceph

# monitor_interface:
monitor_address: 192.168.70.10
# radosgw_interface:
# radosgw_address:

devices: "{{ hostvars['testbed-node-0.osism.local']['ansible_local']['testbed_ceph_devices'] | default([]) }}"
